# Generated by Django 5.2.8 on 2026-03-04 21:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('priority', models.IntegerField(default=0)),
                ('timeout_ms', models.IntegerField(default=10000)),
                ('max_attempts', models.IntegerField(default=3)),
                ('attempts', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('RETRY', 'Retry'), ('DEAD', 'Dead')], default='CREATED', max_length=20)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('type', 'idempotency_key'), name='unique_job_type_idempotency_key')],
            },
        ),
    ]
