# Generated by Django 5.2.8 on 2026-03-13 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_job_error_job_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='job',
            name='unique_job_type_idempotency_key',
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('user', 'type', 'idempotency_key'), name='unique_job_type_idempotency_key'),
        ),
    ]
